### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sethlugibihl**

### CODE REVIEW

**Comment by viktorahlstrom** [comment]
Hey - I noticed you're making multiple pull requests. It's better to make one pull request and add your commits to that one.

**Comment by sethlugibihl** [comment]
What is the best way to merge pull requests?

**Comment by viktorahlstrom** [comment]
Get a clean fork of `karan/Projects-Solutions`. Go to `karan/Projects-Solutions` (this page) and edit README.md. When you commit your changes, make a pull request. If you add more later on, go to `patch-1` in your fork, edit the file and commit.

**Comment by karan** [comment]
Merging it for now. Thanks @viktorahlstrom!

**Pull request merged**
