### PR TITLE
Added Pi and E solutions in Python

### PR DESCRIPTION
**Pull request by rlingineni**

### CODE REVIEW

**Comment by viktorahlstrom** [comment]
Hey @karan - this is able to be merged!

**Comment by rlingineni** [comment]
Hey @karan , do you think you could clear a couple of the pull requests?

**Comment by viktorahlstrom** [comment]
@karan This could require some attention, it can be merged.

**Comment by viktorahlstrom** [comment]
@karan This is still able to be merged!

**Pull request merged**
